Add error filter & add program and session codes params to routes
ApplETS/planifETS-backend pull request #17
Opened 2024-04-20 08:36 UTC by mhd-hi

Add error filter 
#7 
Add program and session codes params to routes. Instead of sending the whole pdf url as a parameter, we can now send program and session codes.
#11

2024-05-08 22:43 UTC, XavierPaquet-Rapold requested changes

2024-05-08 22:43 UTC, XavierPaquet-Rapold commented on src/pdf/pdf-parser/planification/planification-cours.service.ts
> +  // private readonly COURS_X_AXIS = 1.648;
Pourquoi juste commenter et pas enlever ?

2024-05-10 00:36 UTC, mhd-hi commented on src/pdf/pdf-parser/horaire/horaire-cours.service.ts
> +  // private readonly START_PAGE_CONTENT_Y_AXIS = 14.019;
fixed

2024-05-10 00:36 UTC, mhd-hi commented on src/pdf/pdf-parser/planification/planification-cours.service.ts
> +  // private readonly COURS_X_AXIS = 1.648;
fixed

2024-05-19 01:18 UTC, XavierPaquet-Rapold approved these changes

2024-05-19 01:54 UTC, merged