Refactor/add models nestjs standards
ApplETS/planifETS-backend pull request #29
Opened 2024-07-23 22:57 UTC by mhd-hi

## Changes

## Related issues
#26

2024-07-28 23:30 UTC, XavierPaquet-Rapold requested changes

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on prisma/schema.prisma
> +  H
Utilise les noms complets

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on prisma/schema.prisma
> +  trimester Trimester
`term`

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on src/common/api-helper/ets/course/ets-course.controller.ts
> +@Controller('ets/courses')
Pourquoi mettre `ets` dans le chemin ?

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on src/common/api-helper/ets/course/ets-course.controller.ts
> +    return this.etsCourseService.fetchCoursesById('349682,349710');
Tu n'utilise pas l'id ici ?

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on src/common/api-helper/ets/scraper/services/program-page/course-details.interface.ts
Duplicate

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on src/common/api-helper/ets/scraper/services/course-page/course.interface.ts
Duplicate

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on src/common/website-helper/pdf/pdf-parser/planification/planification-cours.service.ts
> +  public async parsePdfFromUrl(pdfUrl: string): Promise<IPlanificationCours[]> {
`ICoursePlanification`

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on src/common/website-helper/pdf/pdf-parser/planification/planification-cours.service.ts
> +  public parsePlanificationCoursPdf(
`parseCoursePlanificationPdf`

2024-07-28 23:30 UTC, XavierPaquet-Rapold commented on src/common/website-helper/pdf/pdf-parser/planification/planification-cours.types.ts
> +export interface IPlanificationCours {
`ICoursePlanification`

2024-07-29 00:12 UTC, mhd-hi commented on prisma/schema.prisma
> +  trimester Trimester
c'est pas la meme chose? term et trimester

2024-07-29 00:13 UTC, mhd-hi commented on src/common/api-helper/ets/course/ets-course.controller.ts
> +@Controller('ets/courses')
pcq cette route "ets/courses" c'est un api wrapper. Et la route "courses" c'est les cours que j'ai dans la bd

2024-07-29 00:19 UTC, mhd-hi commented on src/common/website-helper/pdf/pdf-parser/planification/planification-cours.service.ts
> +  public async parsePdfFromUrl(pdfUrl: string): Promise<IPlanificationCours[]> {
fixed

2024-07-29 00:19 UTC, mhd-hi commented on src/common/website-helper/pdf/pdf-parser/planification/planification-cours.types.ts
> +export interface IPlanificationCours {
fixed

2024-07-29 00:20 UTC, mhd-hi commented on src/common/api-helper/ets/scraper/services/program-page/course-details.interface.ts
j'ai supprimé le dossier scraper pcq on en aura plus besoin

2024-07-29 00:20 UTC, mhd-hi commented on src/common/api-helper/ets/course/ets-course.controller.ts
> +    return this.etsCourseService.fetchCoursesById('349682,349710');
fixed

2024-07-29 00:23 UTC, mhd-hi commented on prisma/schema.prisma
> +  trimester Trimester
![image](https://github.com/user-attachments/assets/f97927d4-ca85-4f75-9350-90705cbd40c3)

2024-07-29 00:25 UTC, mhd-hi commented on prisma/schema.prisma
> +  trimester Trimester
lol je vais juste utiliser session

2024-08-03 04:45 UTC, mhd-hi commented on prisma/schema.prisma
> +  H
fixed

2024-08-03 04:49 UTC, mhd-hi commented on src/common/api-helper/ets/scraper/services/course-page/course.interface.ts
j'ai supprimé le dossier scraper pcq on en aura plus besoin

2024-08-03 04:49 UTC, mhd-hi commented on src/common/website-helper/pdf/pdf-parser/planification/planification-cours.service.ts
> +  public parsePlanificationCoursPdf(
fixed

2024-08-03 04:54 UTC, mhd-hi commented on src/common/api-helper/ets/scraper/services/course-page/course.interface.ts
removed

2024-08-26 19:09 UTC, XavierPaquet-Rapold approved these changes

2024-08-26 19:10 UTC, merged